"""Tests for the Gerrit REST client.

We swap the internal httpx.Client with one that uses httpx.MockTransport so
we can assert both request shape and response parsing without hitting a real
Gerrit server.
"""

from __future__ import annotations

import base64
import json

import httpx
import pytest

from gerrit_ai_reviewer.gerrit import GerritClient, GerritError

XSSI = ")]}'\n"


def _install_mock(client: GerritClient, handler) -> list[httpx.Request]:
    """Replace client._client with a MockTransport-backed Client.

    Returns a list that gets appended with every outgoing Request, so tests
    can assert URL/body/auth after the call.
    """
    recorded: list[httpx.Request] = []

    def wrapped(request: httpx.Request) -> httpx.Response:
        recorded.append(request)
        return handler(request)

    client._client.close()
    client._client = httpx.Client(
        auth=("u", "p"),
        headers={"Accept": "application/json"},
        transport=httpx.MockTransport(wrapped),
    )
    return recorded


def _make_client() -> GerritClient:
    return GerritClient(base_url="https://gerrit.example.com", user="u", http_password="p")


def test_get_change_strips_xssi_prefix():
    payload = {"_number": 1, "project": "demo", "subject": "hi", "current_revision": "abc"}
    body = XSSI + json.dumps(payload)

    client = _make_client()
    recorded = _install_mock(
        client,
        lambda req: httpx.Response(200, text=body, headers={"Content-Type": "application/json"}),
    )
    with client:
        got = client.get_change("12345")

    assert got == payload
    assert len(recorded) == 1
    req = recorded[0]
    assert req.method == "GET"
    assert req.url.path == "/a/changes/12345"
    # Authenticated prefix + options
    options = req.url.params.get_list("o")
    assert "CURRENT_REVISION" in options
    assert "CURRENT_FILES" in options


def test_get_patch_base64_decoded():
    original = "diff --git a/foo b/foo\n--- a/foo\n+++ b/foo\n@@ -1 +1 @@\n-a\n+b\n"
    b64 = base64.b64encode(original.encode()).decode()

    client = _make_client()
    _install_mock(client, lambda req: httpx.Response(200, text=b64))
    with client:
        got = client.get_patch("12345")

    assert got == original


def test_post_review_payload_shape():
    captured: dict = {}

    def handler(req: httpx.Request) -> httpx.Response:
        captured["method"] = req.method
        captured["path"] = req.url.path
        captured["body"] = json.loads(req.content.decode())
        return httpx.Response(200, text=XSSI + "{}")

    client = _make_client()
    _install_mock(client, handler)
    with client:
        client.post_review(
            change_id="42",
            revision="current",
            message="hi",
            comments={"src/a.py": [{"line": 3, "message": "[warn] x"}]},
            labels={"Code-Review": 0},
        )

    assert captured["method"] == "POST"
    assert captured["path"] == "/a/changes/42/revisions/current/review"
    body = captured["body"]
    assert body["message"] == "hi"
    assert body["comments"] == {"src/a.py": [{"line": 3, "message": "[warn] x"}]}
    assert body["labels"] == {"Code-Review": 0}
    assert body["tag"] == "autogenerated:ai-review"


def test_error_status_raises_gerrit_error():
    client = _make_client()
    _install_mock(client, lambda req: httpx.Response(404, text="not found"))
    with client, pytest.raises(GerritError) as exc:
        client.get_change("nope")
    assert "404" in str(exc.value)
