"""Gerrit REST API client.

Docs: https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html
Gerrit JSON responses are prefixed with `)]}'\\n` for XSSI protection; strip it.
Authenticated endpoints live under `/a/`.
"""
from __future__ import annotations

import base64
import json
from typing import Any

import httpx

_XSSI_PREFIX = ")]}'\n"


class GerritError(RuntimeError):
    pass


class GerritClient:
    def __init__(self, base_url: str, user: str, http_password: str, timeout: float = 30.0):
        self._base = base_url.rstrip("/")
        self._client = httpx.Client(
            auth=(user, http_password),
            timeout=timeout,
            headers={"Accept": "application/json"},
        )

    def close(self) -> None:
        self._client.close()

    def __enter__(self) -> "GerritClient":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()

    # --- low level ---------------------------------------------------------

    def _url(self, path: str) -> str:
        if not path.startswith("/"):
            path = "/" + path
        return f"{self._base}/a{path}"

    def _get_json(self, path: str, params: dict[str, Any] | None = None) -> Any:
        r = self._client.get(self._url(path), params=params)
        if r.status_code >= 400:
            raise GerritError(f"GET {path} -> {r.status_code}: {r.text[:300]}")
        text = r.text
        if text.startswith(_XSSI_PREFIX):
            text = text[len(_XSSI_PREFIX):]
        return json.loads(text)

    def _get_text(self, path: str, params: dict[str, Any] | None = None) -> str:
        r = self._client.get(self._url(path), params=params)
        if r.status_code >= 400:
            raise GerritError(f"GET {path} -> {r.status_code}: {r.text[:300]}")
        return r.text

    def _post_json(self, path: str, payload: dict[str, Any]) -> Any:
        r = self._client.post(
            self._url(path),
            json=payload,
            headers={"Content-Type": "application/json"},
        )
        if r.status_code >= 400:
            raise GerritError(f"POST {path} -> {r.status_code}: {r.text[:300]}")
        text = r.text
        if text.startswith(_XSSI_PREFIX):
            text = text[len(_XSSI_PREFIX):]
        return json.loads(text) if text.strip() else None

    # --- high level --------------------------------------------------------

    def get_change(self, change_id: str) -> dict[str, Any]:
        """Fetch change detail with current revision, files, commit, labels."""
        opts = [
            "CURRENT_REVISION",
            "CURRENT_COMMIT",
            "CURRENT_FILES",
            "DETAILED_LABELS",
            "DETAILED_ACCOUNTS",
            "MESSAGES",
        ]
        params = [("o", o) for o in opts]
        return self._get_json(f"/changes/{change_id}", params=params)

    def get_patch(self, change_id: str, revision: str = "current") -> str:
        """Return unified diff (decoded) for a revision via the /patch endpoint."""
        r = self._client.get(
            self._url(f"/changes/{change_id}/revisions/{revision}/patch"),
            params={"zip": "false"},
        )
        if r.status_code >= 400:
            raise GerritError(f"get_patch {change_id} -> {r.status_code}: {r.text[:300]}")
        # Gerrit returns base64 text body.
        try:
            return base64.b64decode(r.text).decode("utf-8", errors="replace")
        except Exception as e:
            raise GerritError(f"decode patch failed: {e}") from e

    def get_file_diff(self, change_id: str, file_path: str, revision: str = "current") -> dict[str, Any]:
        """Structured per-file diff (content sections with a/b tags)."""
        # Gerrit requires the path URL-encoded with %2F for slashes; httpx does that.
        return self._get_json(f"/changes/{change_id}/revisions/{revision}/files/{file_path}/diff")

    def list_files(self, change_id: str, revision: str = "current") -> dict[str, Any]:
        return self._get_json(f"/changes/{change_id}/revisions/{revision}/files")

    def post_review(
        self,
        change_id: str,
        revision: str,
        message: str,
        comments: dict[str, list[dict[str, Any]]] | None = None,
        labels: dict[str, int] | None = None,
        tag: str | None = "autogenerated:ai-review",
    ) -> Any:
        """POST /changes/{id}/revisions/{rev}/review.

        comments: {file_path: [{line, message, ...}, ...]}
        labels:   {"Code-Review": 0} — AI does not vote by default.
        """
        payload: dict[str, Any] = {"message": message}
        if comments:
            payload["comments"] = comments
        if labels:
            payload["labels"] = labels
        if tag:
            payload["tag"] = tag
        return self._post_json(
            f"/changes/{change_id}/revisions/{revision}/review",
            payload,
        )
